name: On Merge Flow

on:
  push:
    branches:
      - release
    paths:
      - linux-amd64.Dockerfile
      - linux-arm64.Dockerfile
      - VERSION.json

jobs:
  build:
    permissions:
      contents: write
      packages: write
    uses: runlix/build-workflow/.github/workflows/on-merge.yml@main
    secrets: inherit

